
pipeline {
    agent any

    stages {
        stage('stage-1') {
            steps {
                echo 'Stage 1...'
            }
        }
        stage('stage-2') {
            steps {
                echo 'Stage 2...'
            }
        }
        stage('stage-3') {
            steps {
                echo 'Stage 3...'
            }
        }
    }

    post {
        always {
            echo 'This will always run after the stages.'
        }
        success {
            echo 'This will run only if the pipeline succeeds.'
        }
        failure {
            echo 'This will run only if the pipeline fails.'
        }
    }
}